### ISSUE TITLE
Unable to load rails credentials due to special character at the start of the string

### ISSUE THREAD

**Issue by RailsCod3rFuture** [Shopify/ejson-rails#65]
I came across a very unique issue where Psych is failing to parse the secrets.json file due to a special character in the password. The example below should hopefully explain the behavior that I'm getting -- seems like its having an encoding issue through Psyche.

**secrets.json**
```
"development": {
 "user": "okname",
"password": "$$@@#password"
}
```

**database.yml**
```
development:
   ....
   username: <%= Rails.application.credentials[Rails.env.to_sym].dig(:user) %>
   password: <%= Rails.application.credentials[Rails.env.to_sym].dig(:password) %>
```

You should receive the error below when starting up your rails console in the env or rails server in the env

`in `parse': (<unknown>): did not find expected node content while parsing a block node at line 16 column 13 (Psych::SyntaxError)`
